import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Layout from "@/components/Layout";
import ProfilePic from "../../public/images/Akbar.png";
import AnimatedText from "@/components/AnimatedText";
import { ExternalLinkIcon } from "@/components/Icons";
import HireMe from "@/components/HireMe";

export default function Home() {
    return (
        <>
            <Head>
                <title>Portofolio with NextJS | Home</title>
                <meta name="description" content="Generated by Create next app" />
            </Head>
            <main>
                <div className="flex items-center w-full min-h-screen text-dark dark:text-light">
                    <Layout className="pt-0 pl-60">
                        <div className="flex items-center justify-between w-full">
                            <div className="w-1/3">
                                <Image src={ProfilePic} alt="AkbarWP" className="w-full h-auto" priority />
                            </div>

                            <div className="flex flex-col items-center self-center w-1/2">
                                <p className="font-medium">Hai, how are you today? 👋 My name is </p>
                                <AnimatedText text="Akbar Wibowo Putra" className="text-6xl text-left dark:text-light" />
                                <p className="my-4 text-base font-medium">
                                    I am a college student from Universitas Dinamika (Stikom Surabaya). And I majored in Information Systems. I am currently interested in Web Development on the Backend Developer. And also I am studying the PHP framework is Laravel. and as a complement I also learn ReactJS for the Front-end.
                                </p>

                                <div className="flex items-center self-start mt-2">
                                    <Link href="/curriculum-vitae.pdf" target={"_blank"} className="flex items-center p-2.5 px-6 bg-dark dark:bg-light text-light dark:text-dark rounded-lg text-lg font-semibold hover:bg-light hover:dark:bg-dark hover:text-dark hover:dark:text-light border-2 border-solid border-transparent hover:border-dark hover:dark:border-light transition">
                                        Resume <span className="mr-1"></span>
                                        <ExternalLinkIcon className={"w-6 h-6"} />
                                    </Link>

                                    <Link href="https://www.instagram.com/akbarwp002/" target={"_blank"} className="ml-4 text-lg font-medium capitalize text-dark dark:text-light underline ">
                                        Contact Me
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </Layout>
                </div>
                <HireMe />
            </main>
        </>
    );
}
