import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Layout from "@/components/Layout";
import ProfilePic from "../../public/images/Akbar.png";
import AnimatedText from "@/components/AnimatedText";
import { ExternalLinkIcon } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
    return (
        <>
            <Head>
                <title>Portofolio with NextJS | Home</title>
                <meta name="description" content="Generated by Create next app" />
            </Head>
            <TransitionEffect />
            <main>
                <div className="flex items-center w-full min-h-screen text-dark dark:text-light">
                    <Layout className="pt-8 lg:pt-0">
                        <div className="flex flex-col lg:flex-row items-center justify-between w-full">
                            <div className="w-full md:w-1/2 lg:w-1/3 mb-10 lg:mb-0">
                                <Image src={ProfilePic} alt="AkbarWP" className="w-full h-auto" priority />
                            </div>

                            <div className="flex flex-col items-center self-center w-full lg:w-1/2">
                                <p className="mb-3 lg:mb-0 font-medium text-sm md:text-base">Hai, how are you today? 👋 My name is </p>
                                <AnimatedText text="Akbar Wibowo Putra" className="text-4xl lg:text-5xl xl:text-6xl text-center lg:text-left dark:text-light" />
                                <p className="my-4 text-lg lg:text-base font-medium text-center lg:text-left">
                                    I am a college student from Universitas Dinamika (Stikom Surabaya). And I majored in Information Systems. I am currently interested in Web Development on the Backend Developer. And also I am studying the PHP framework is <span className="text-[#FF2D20]">Laravel</span>. and as a complement I also learn <span className="text-[#61DAFB]">ReactJS</span> for the Front-end.
                                </p>

                                <div className="flex flex-col md:flex-row items-center justify-center lg:self-start mt-2 gap-y-3 md:gap-y-0 md:gap-x-3 lg:gap-x-0">
                                    <Link href="/curriculum-vitae.pdf" target={"_blank"} className="flex items-center p-1.5 px-3 md:p-2.5 md:px-6 bg-dark dark:bg-light text-base md:text-lg text-light dark:text-dark rounded-lg font-semibold hover:bg-light hover:dark:bg-dark hover:text-dark hover:dark:text-light border-2 border-solid border-transparent hover:border-dark hover:dark:border-light transition">
                                        Resume <span className="mr-1"></span>
                                        <ExternalLinkIcon className={"w-6 h-6"} />
                                    </Link>

                                    <Link href="https://www.instagram.com/akbarwp002/" target={"_blank"} className="lg:ml-4 text-base md:text-lg font-medium capitalize text-dark dark:text-light underline ">
                                        Contact Me
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </Layout>
                </div>
                <HireMe />
            </main>
        </>
    );
}
